# Generated by Django 5.1.2 on 2024-11-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0002_questao'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='questoes_imagens/'),
        ),
    ]
