# Generated by Django 5.1.2 on 2024-11-18 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0004_questionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='questoes',
            field=models.ManyToManyField(related_name='questionarios', to='prog.questao'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=1)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prog.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
