# Generated by Django 5.1.2 on 2024-11-19 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0005_alter_questionario_questoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostausuario',
            name='correta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respostausuario',
            name='questionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prog.questionario'),
        ),
        migrations.AlterField(
            model_name='respostausuario',
            name='resposta',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
