# Generated by Django 5.1.2 on 2024-11-19 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0007_alter_respostausuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostausuario',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='respostausuario',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prog.questionario'),
        ),
    ]
