# Generated by Django 5.1.2 on 2024-11-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0008_respostausuario_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostausuario',
            name='session_key',
        ),
        migrations.AlterField(
            model_name='respostausuario',
            name='correta',
            field=models.BooleanField(),
        ),
    ]
