# Generated by Django 5.1.2 on 2024-11-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0009_remove_respostausuario_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostausuario',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
