# Generated by Django 5.1.3 on 2024-11-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog', '0011_questionario_prazo_disponibilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='dica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
